@host=localhost
@port=4004
@protocol=http
@authUser=dummy.user@com
@authPassword=initial


###
POST {{protocol}}://{{host}}:{{port}}/odata/v4/embedding-storage/Files HTTP/1.1
Content-Type: application/json
Authorization: Basic {{authUser}} {{authPassword}}

{
 "ID":"7a6b186b-57fd-4baa-9098-4906b4800275",
 "mediaType":"appication/json",
 "fileName":"monopoly.pdf",
 "size":"1049"
}

###
PUT {{protocol}}://{{host}}:{{port}}/odata/v4/embedding-storage/Files(7a6b186b-57fd-4baa-9098-4906b4800275)/content HTTP/1.1
Content-Type: application/pdf
Authorization: Basic {{authUser}} {{authPassword}}



< ./monopoly.pdf

###
GET {{protocol}}://{{host}}:{{port}}/odata/v4/embedding-storage/Files(7a6b186b-57fd-4baa-9098-4906b4800275)/content
Content-Type: application/octet-stream
Authorization: Basic {{authUser}} {{authPassword}}

###
GET {{protocol}}://{{host}}:{{port}}/odata/v4/embedding-storage/Files(7a6b186b-57fd-4baa-9098-4906b4800275)/content
Content-Disposition: 'attachment; filename="myPDF.pdf"'
Authorization: Basic {{authUser}} {{authPassword}}

###
POST {{protocol}}://{{host}}:{{port}}/odata/v4/embedding-storage/storeEmbeddings
Content-Type: application/json
Authorization: Basic {{authUser}} {{authPassword}}

{
    "uuid":"7a6b186b-57fd-4baa-9098-4906b4800275"
}

###
POST {{protocol}}://{{host}}:{{port}}/odata/v4/chat/Conversation
Content-Type: application/json
Authorization: Basic {{authUser}} {{authPassword}}

{
  "cID": "7a6b186b-57fd-4baa-9098-4906b4800275",
  "userID": "dummy.user@com",
  "creation_time": "2017-04-13T15:51:04.0000000Z",
  "last_update_time": "2017-04-13T15:51:04.0000000Z",
  "title": "Bhargav Chat",
  "to_messages": [
    {
      "cID_cID": "7a6b186b-57fd-4baa-9098-4906b4800275",
      "mID": "7a6b186b-57fd-4baa-9098-4906b4800275",
      "role": "user",
      "content": "sample message",
      "creation_time": "2017-04-13T15:51:04.0000000Z"
    }
  ]
}

###
POST {{protocol}}://{{host}}:{{port}}/odata/v4/chat/getChatRagResponse
Content-Type: application/json
Authorization: Basic {{authUser}} {{authPassword}}

{
  "conversationId": "7a6b186b-57fd-4baa-9098-4906b4800275",
  "messageId": "c74eb40e-c1d5-483a-bcd1-4e2cca2dae7a",
  "message_time": "2017-04-13T15:51:04.0000000Z",
  "user_id": "dummy.user@com",
  "user_query": "how many players can play monopoly"
}

###
POST {{protocol}}://{{host}}:{{port}}/odata/v4/chat/getChatRagResponse
Content-Type: application/json
Authorization: Basic {{authUser}} {{authPassword}}

{
  "conversationId": "7a6b186b-57fd-4baa-9098-4906b4800275",
  "messageId": "5449cd4d-d54b-48b6-86c3-80cfebc07710",
  "message_time": "2017-04-13T15:51:04.0000000Z",
  "user_id": "dummy.user@com",
  "user_query": "hopw much money a player can have in monopoly"
}